Repository bitwyre/megaphone, pull requests merged in 2023-10, with the labels that each got.

#25 feat(megaphone): Add entrypoint & Adjust Dockerfile for vault injection
  Dockerfile
  entrypoint.sh
Labels: size/S

#24 feat(megaphone): kdb+ integration
  .gitignore
  Makefile
  SPSCQueue.hpp
  c.o
  k.h
  megaphone.cpp
Labels: size/XXL

#26 fix(megaphone): table column count fix
  megaphone.cpp
Labels: size/XS

#28 fix(megaphone): fix kdb memory overflow
  megaphone.cpp
Labels: size/M

#29 fix(megaphone): immediate buffer flush for debugging
  megaphone.cpp
Labels: size/S

#32 fix(megaphone):fix trades
  megaphone.cpp
Labels: size/XS

#33 fix(megaphone):fix qty timestamps
  megaphone.cpp
Labels: size/S

#34 fix(megaphone): remove redundancy in json
  megaphone.cpp
Labels: size/S

#35 fix(megaphone): integrate ticker tickerplant consumer
  megaphone.cpp
Labels: size/M

#36 infra(fix): fix copy DIR to Container
  Dockerfile
Labels: size/XS
